Add and Delete note
Jay-Gadhiya/cheer-notes pull request #4
Opened 2022-03-29 13:14 UTC by Jay-Gadhiya

Test Link: https://cheer-notes-p2y6wh73x-jay-gadhiya.vercel.app/

Feature : Add note, Delete note

Context: notesActions-context.jsx
Reducer :  notesActions-reducer.jsx

2022-03-29 15:03 UTC, RahullRawat approved these changes
**Just one suggestion that user shouldn't be able to add an empty note.** 

- Other than this everything looks good to me
- Good naming conventions and well formatted code

Great work @Jay-Gadhiya

2022-03-29 15:03 UTC, RahullRawat commented on src/Utilities-Functions/addNote.jsx
> +        console.log(res);
You can remove these unwanted `console.log`

2022-03-29 15:03 UTC, RahullRawat commented on src/Utilities-Functions/addNote.jsx
> +        console.log(err);
You can remove these unwanted `console.log`

2022-03-29 15:03 UTC, RahullRawat commented on src/Utilities-Functions/deleteNote.jsx
> +        console.log(error);
You can remove these unwanted `console.log`

2022-03-30 03:37 UTC, gopalbbharadva commented on src/Contexts/notesActions-context.jsx
> +
Suggestion: without require we can also import it by using normal "import"

2022-03-30 03:39 UTC, jeetbhalani15 approved these changes
Remove logs after debuging.
Use Context & reducer are working fine.
Clean Name & readable code.

2022-03-30 03:39 UTC, gopalbbharadva commented on src/Pages/Home/Home.jsx
> +    }
Improvement: Add note only if response status is 201. remove unused consoles.

2022-03-30 03:40 UTC, AtulPant2704 commented on src/Reducers/notesActions-reducer.jsx
> +            return {...state, notes : [...action.payload] };
Over here you can just write :- `return {...state, notes : action.payload };` and that would also work, why to destructure unnecessarily.

2022-03-30 03:42 UTC, gopalbbharadva requested changes
Bug: Note is adding one or both of the inputs are not given. just add validation required on both inputs.

2022-03-30 03:43 UTC, AtulPant2704 approved these changes
Other than the one change mentioned, rest all looks good. One point that Rahul has already mentioned do work on it, in upcoming PRs atleast `Title `should be provided by the user. Good naming convention with properly formatted data, made it really easy to review.

2022-03-30 04:29 UTC, Jay-Gadhiya commented
> **Just one suggestion that user shouldn't be able to add an empty note.**
> 
> * Other than this everything looks good to me
> * Good naming conventions and well formatted code
> 
> Great work @Jay-Gadhiya

I Implemented it, thanks for the suggestion.

2022-03-30 04:30 UTC, merged